In [5]:
#Array Calculation
#Sum
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a.shape

(2, 3)

In [11]:
a.sum()

21

In [19]:
aa=a.sum(axis=1)
print(aa)
print(aa.shape)

[ 6 15]
(2,)


In [25]:
a=np.ones((5,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [27]:
a.shape

(5, 6)

In [33]:
a.sum(axis=0).shape
a.sum(axis=0)

array([5., 5., 5., 5., 5., 5.])

In [32]:
a.sum(axis=1).shape
a.sum(axis=1)

array([6., 6., 6., 6., 6.])

In [ ]:
#Other Methods & Functions
#Mathematical Functions
    #sum,prod
    #min,max,argmin,argmax
    #ptp(max-min)
#Statistics
    #mean,std,var
#Truth value testing
    #any, all

In [35]:
#Sum Function
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.sum(a)

21

In [38]:
np.sum(a,axis=0)

array([5, 7, 9])

In [61]:
a=np.array([[2,3],[0,1]])
a

array([[2, 3],
       [0, 1]])

In [62]:
np.min(a)
np.min(a,axis=0)

array([0, 1])

In [63]:
np.max(a,axis=0)
np.max(a)

3

In [64]:
#argmin/argmax
#To get the location of min & max. arg method return the location of min & max in 1D
a.argmax()

1

In [65]:
a.argmin()

2

In [68]:
np.argmin(a)

2

In [66]:
np.unravel_index(a.argmax(),a.shape)

(0, 1)

In [81]:
#where
a=np.array([-1,2,5,5])
a==a.max()

array([False, False,  True,  True])

In [83]:
np.where(a==a.max())

(array([2, 3], dtype=int64),)

In [84]:
np.where(a>0)

(array([1, 2, 3], dtype=int64),)