In [23]:
#Numpy
import numpy as np
a=np.array([1,2,3,4])
f=np.array([1.2,3.4,5.6,2.5])


In [18]:
#Type of element in array
type(a)

numpy.ndarray

In [17]:
#Dimension of array
a.ndim

1

In [15]:
#Return Tuples with number of element in array (row,col)
a.shape

(4,)

In [16]:
#Return number of element in array
a.size

4

In [22]:
a[1]=10
a

array([ 1, 10,  3,  4])

In [40]:
#Multiplication of 2 Numpy array
a*f

array([ -2.4,  -6.8, -11.2,  -5. ])

In [25]:
#Addition of 2 array
a+f

array([2.2, 5.4, 8.6, 6.5])

In [31]:
f-a

array([ 0.2,  1.4,  2.6, -1.5])

In [32]:
f**a

array([  1.2   ,  11.56  , 175.616 ,  39.0625])

In [29]:
f/a

array([1.2       , 1.7       , 1.86666667, 0.625     ])

In [14]:
#Constant Multiplication
a*10

array([10, 20, 30, 40])

In [11]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [35]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [39]:
a.fill(-2.6)
a

array([-2, -2, -2, -2])

In [45]:
#2D Array
b=np.array([[0,1,2,3],[10,11,12,13]])
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [46]:
b.shape

(2, 4)

In [48]:
b.size

8

In [47]:
b.ndim

2

In [50]:
#get/set 2D array
b[1,2]

12

In [52]:
b[1,2]=21
b

array([[ 0,  1,  2,  3],
       [10, 11, 21, 13]])

In [53]:
b[0]

array([0, 1, 2, 3])

In [55]:
#Slicing var[lower:upper:setp]
a=np.array([10,11,12,13,14])
a

array([10, 11, 12, 13, 14])

In [56]:
a[1:3]

array([11, 12])

In [57]:
a[1:-2]

array([11, 12])

In [59]:
a[-4:3]

array([11, 12])

In [60]:
#Omitted boundaries are assumed to be the begining or end of the list
a[:3]

array([10, 11, 12])

In [61]:
a[-2:]

array([13, 14])

In [62]:
a[::2]

array([10, 12, 14])

In [88]:
#var[lower:upper:setp,lower:upper:setp]
c=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],
            [30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])

c

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [89]:
c[0,3:5]

array([3, 4])

In [90]:
c[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [91]:
c[4:,4:]

array([[44, 45],
       [54, 55]])

In [92]:
c[2::2,0::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [93]:
c.ndim

2

In [95]:
d=np.arange(25).reshape(5,5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [98]:
d[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [99]:
d[4,:]

array([20, 21, 22, 23, 24])

In [103]:
d[1::2,0:3:2]

array([[ 5,  7],
       [15, 17]])

In [130]:
e=np.array([1,2,3,4])
e

array([1, 2, 3, 4])

In [118]:
f=e[:2]
f

array([1, 2])

In [119]:
f[0]

1

In [121]:
f[0]=-1
f

array([-1,  2])

In [122]:
e

array([-1,  2,  3,  4])

In [126]:
a=np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [127]:
a[-2:]

array([3, 4])

In [131]:
a[-2:]=[6,7]
a

array([0, 1, 2, 6, 7])

In [132]:
a[-2:]=11
a

array([ 0,  1,  2, 11, 11])

In [134]:
#Syntactical Sugar '__' Dunder method, special method, Pyhton data model; FLuent Pyhton book
#np.array.__call__([1,2,3,4,5])
a=np.array([1,2,3,4,5])
a[0]
#__getitem__(0)
a[0]=10
#__setitem__(0,10)
a

array([10,  2,  3,  4,  5])

In [142]:
#Fancy Indexing
#Indexing by Position
a=np.arange(0,80,10)
print(a)
indices=[1,2,-3]
y=a[indices]
print(y)
a[indices]=99
a

[ 0 10 20 30 40 50 60 70]
[10 20 50]


array([ 0, 99, 99, 30, 40, 99, 60, 70])

In [143]:
#Indexing by Booleans
#Manual Creation of Index
mask=np.array([0,1,1,0,0,1,0,0],dtype=bool)
mask

array([False,  True,  True, False, False,  True, False, False])

In [145]:
#Fancy Indexing
print(y)
y=a[mask]
y

[10 20 50]


array([99, 99, 99])

In [146]:
a=np.array([-1,-2,1,4,-6,9,3])
a

array([-1, -2,  1,  4, -6,  9,  3])

In [149]:
Negative=a<0
a[Negative]

array([-1, -2, -6])

In [150]:
a[Negative]=0
a

array([0, 0, 1, 4, 0, 9, 3])

In [168]:
#Fancy Indexing in 2-D
c=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],
            [30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
c

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [169]:
c[[0,1,2,3,4],[1,2,3,4,5,]]

array([ 1, 12, 23, 34, 45])

In [158]:
c[3::,[0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [170]:
mask=np.array([1,0,1,0,0,1],dtype=bool)
c[mask,2]


array([ 2, 22, 52])

In [171]:
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [179]:
#Extract 2,13,16,19
a[[0,2,3,3],[2,3,1,4]]


array([ 2, 13, 16, 19])

In [175]:
#Extract number divisible by 3
divisibleby3=a%3==0
print(divisibleby3)
a[divisibleby3]

[[ True False False  True False]
 [False  True False False  True]
 [False False  True False False]
 [ True False False  True False]
 [False  True False False  True]]


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])